import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>My Next js App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-center gap-8">
          <div>
            <a href="Add"> Add Product </a>
          </div>
          <div>
            <a href="ProductPage"> Show Product </a>
          </div>
        </div>
      </main>
    </>
  );
}
